### ISSUE TITLE
No property findAll found for type Benefit!

### ISSUE THREAD

**Issue by alesisjoan** [darrachequesne/spring-data-jpa-datatables-sample#2] opened 2016-09-05 02:22 UTC
Exception is thrown: org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type Benefit!

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'benefitRepository'

this is my code:

BenefitRepository
public interface BenefitRepository extends DataTablesRepository<Benefit, Long>{}

BenefitServiceImpl
@Override
    public DataTablesOutput<Benefit> getAll(DataTablesInput input) {
        return repo.findAll(input);
    }

**Comment by darrachequesne** [comment] 2016-09-05 10:56
Hi! I'm afraid I'll need a bit more context to debug that :angel: 

Did you follow the instructions [here](https://github.com/darrachequesne/spring-data-jpa-datatables#how-to-use)? More specifically that line:

`@EnableJpaRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class)`

Could you share your Benefit (and BenefitRepository) classes please?

**Comment by alesisjoan** [comment] 2016-09-06 01:05
OK, inserting @EnableJpaRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class) to the WebAppConfig.java solved my issue.

You can close the issue, but now i have anoter error.

With Ajax call not matching the controller method.

Here is my Controller:

@Controller
@RequestMapping(value = "/Benefit")
public class BenefitController {

    @Autowired
    BenefitDataTableRepo benefitDataTableRepo;

    @JsonView(DataTablesOutput.View.class)
    @RequestMapping(value = "/datatable2", method = RequestMethod.GET)
    public @ResponseBody DataTablesOutput<Benefit> getBenefits2(@Valid DataTablesInput input){
        return benefitDataTableRepo.findAll(input);
    }

}

here is my repo:

public interface BenefitDataTableRepo extends DataTablesRepository<Benefit, Long> {
}


here is js function:

        var table = $('#table_benefits').DataTable({
                                                       'ajax' : '/datatable2',
                                                       'serverSide' : true,
                                                       columns : [ {
                                                           data : 'benefitOid'
                                                       }, {
                                                           data : 'parameter'
                                                       }, {
                                                           data : 'type'
                                                       }, {
                                                           data : 'checked'
                                                       } ]


                                                   });
    });

here is my entity:

@Entity
public class Benefit {

  @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long benefitOid;

    @NotNull
    private String parameter;

    private boolean checked = false;

}

**Comment by darrachequesne** [comment] 2016-09-06 05:00
I see you have two `@RequestMapping`. Shouldn't the url be `/Benefit/datatable2` then?

**Comment by alesisjoan** [comment] 2016-09-06 11:07
> I see you have two @RequestMapping. Shouldn't the url be /Benefit/datatable2 then?
Yep, i realized that after my comment was sent

Url changed to /Benefit/datatable2 but still not working.

**Comment by darrachequesne** [comment] 2016-09-07 20:41
@alesisjoan did you solve your issue? can you debug the request in devtools?

**Comment by darrachequesne** [comment] 2016-10-30 18:20
Closing, please reopen if needed.

**Closed by darrachequesne** 2016-10-30 18:20 UTC

**Comment by tshavkat** [comment] 2019-12-06 09:50
> Hi! I'm afraid I'll need a bit more context to debug that 👼
> 
> Did you follow the instructions [here](https://github.com/darrachequesne/spring-data-jpa-datatables#how-to-use)? More specifically that line:
> 
> `@EnableJpaRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class)`
> 
> Could you share your Benefit (and BenefitRepository) classes please?

Very usefull, thanks very much!

**Comment by anuragdhiman** [comment] 2020-09-26 14:38
Hi there,
Facing the same issue, please help me out,
nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customreProfileRepo': Invocation of init method failed; nested exception is org.springframework.data.mapping.PropertyReferenceException: No property findAll found for type DataTablesOutput!

Below is my code
1. This is my separate configuration class because  I have an already existing class which is invoking base package
```
@Configuration
@EnableMongoRepositories(repositoryFactoryBeanClass = DataTablesRepositoryFactoryBean.class, 
			basePackages = { "com.base.repo.customer" })
public class DataTableConfig {

}

```
2.  A repo class

```
@Repository
public interface CustomerProfileRepo extends DataTablesRepository<CustomerProfile, String>{

}
```

3. Controller class
```
@RequestMapping(value ="/customer/list", method = RequestMethod.GET)
	    public DataTablesOutput<CustomerProfile> list(@Valid DataTablesInput input) {
	        return customerProfileRepo.findAll(input);
	    }
```

**Comment by darrachequesne** [comment] 2020-09-30 16:03
@anuragdhiman Hi! Would you be able to reproduce your issue by forking this [repo](https://github.com/darrachequesne/spring-data-mongodb-datatables-sample)? If you are actually able to reproduce, could you please open a new issue with all necessary details? Thanks!

**Comment by anuragdhiman** [comment] 2020-09-30 16:20
@darrachequesne Thanks for sharing this. Sure I will try the same and get back!
