### ISSUE TITLE
Search with column regex=true not working

### ISSUE THREAD

**Issue by pshingavi** [darrachequesne/spring-data-jpa-datatables-sample#5] opened 2016-10-07 17:42 UTC
Hi,

I am trying to search a column with server side processing enabled. Regex search works without server side processing. I have a list of strings and want to do a search using regex string on a specific column, example regex : '^str1|str2|str3|^str4$'.

I am sending the columns[index].search.regex=true with it's corresponding value columns[index].search.value=myregex, I find no results. But it works for non-regex individual values. Am I missing anything ?

Thanks in advance !

**Comment by darrachequesne** [comment] 2016-10-30 18:22
Closed, as duplicate of https://github.com/darrachequesne/spring-data-jpa-datatables/issues/31.

**Closed by darrachequesne** 2016-10-30 18:22 UTC
